Repository vlang/v, pull requests merged in 2019-06, with the labels that each got.

#515 Add arcus functions
  math/math.v
Labels: vlib

#537 parser.v: fixed pub mut handling
  compiler/parser.v
Labels: bug

#534 Add exists method to map
  builtin/map.v
Labels: feature request

#533 Added free() method for StringBuilder
  builtin/string_builder.v
Labels: compiler-specific, feature request

#532 Add all types of int and float to json decode/encode
  compiler/jsgen.v
  json/json_primitives.v
Labels: feature request

#562 added math constants (they must be in PascalCase)
  complex/complex.v
Labels: feature request

#566 Added different functions for casting to integers and strings
  builtin/string.v
Labels: discussion, feature request

#531 Updated colors in gx.v
  gx/gx.v
Labels: clean-up

#554 Update README.md
  README.md
Labels: documentation

#556 Fix Issues #553
  builtin/string.v
Labels: bug

#635 fix order of the `time` struct in the `time` module
  time/time.v
Labels: vlib

#624 Use matrix and add osx build on travis
  .travis.yml
  compiler/Makefile
  glm/glm_test.v
Labels: clean-up

#603 Fix up redundant type declare arguments
  builtin/array.v
  builtin/map.v
  compiler/table.v
  examples/tetris/tetris.v
  gl/gl.v
  os/os.v
Labels: compiler, examples, vlib

#530 add example VCasino
  examples/VCasino/.gitignore
  examples/VCasino/README.md
  examples/VCasino/VCasino.v
Labels: examples

#539 getline: checks if newline at the end to not cut end of line
  os/os.v
Labels: optimization, vlib

#586 removed bits C code inside utf8 builtin
  builtin/utf8.v
Labels: vlib

#591 Make string.index() use a linear KMP search
  builtin/string.v
Labels: vlib

#623 add log and rename colors
  examples/log.v
  log/log.v
  termcolor/colors.v
Labels: vlib

#583 add `unsetenv`, `setenv`, `clearenv` to os module
  os/os.v
  os/os_test.v
Labels: vlib

#462 Fix decl c struct follow a v struct
  compiler/parser.v
Labels: compiler

#528 os.v: getline fixed conditional jump on uninitialized values
  os/os.v
Labels: vlib
