Repository vlang/v, pull requests merged in 2022-10, with the labels that each got.

#15947 fmt: keep `volatile` ident in global decl
  vlib/v/fmt/fmt.v
  vlib/v/fmt/tests/global_keep.vv
Labels: Hacktoberfest, hacktoberfest-accepted

#15945 maps: Init `maps` module, add `filter`, `flat_map`, `maps` functions
  vlib/maps/README.md
  vlib/maps/maps.v
  vlib/maps/maps_test.v
Labels: Hacktoberfest

#15949 native: support for compile-time conditionals
  vlib/v/gen/native/amd64.v
  vlib/v/gen/native/comptime.v
  vlib/v/gen/native/gen.v
  vlib/v/gen/native/tests/atexpr.vv
  vlib/v/gen/native/tests/atexpr.vv.out
  vlib/v/gen/native/tests/comptime.vv
  vlib/v/gen/native/tests/comptime.vv.out
  vlib/v/gen/native/tests/native_test.v
Labels: Hacktoberfest

#15932 checker: allow `int` to `enum` cast only inside `unsafe`
  examples/2048/2048.v
  examples/gg/arcs_and_slices.v
  examples/sokol/02_cubes_glsl/cube_glsl.v
  vlib/builtin/linux_bare/linux_syscalls.v
  vlib/builtin/linux_bare/memory_managment.v
  vlib/builtin/string_interpolation.v
  vlib/gg/gg.c.v
  vlib/mysql/orm.v
  vlib/mysql/stmt.c.v
  vlib/net/address.v
  vlib/net/smtp/smtp.v
  vlib/net/websocket/message.v
  vlib/sokol/gfx/gfx_utils.c.v
  vlib/sokol/sgl/sgl.c.v
  vlib/term/ui/termios_nix.c.v
  vlib/toml/tests/encode_and_decode_test.v
  vlib/v/ast/types.v
  vlib/v/checker/checker.v
  vlib/v/checker/tests/casting_numbers_to_enums_outside_unsafe_err.out
  vlib/v/checker/tests/casting_numbers_to_enums_outside_unsafe_err.vv
  vlib/v/checker/tests/enum_cast.out
  vlib/v/checker/tests/enum_cast.vv
  vlib/v/doc/doc.v
  vlib/v/gen/native/tests/enum.vv
  vlib/v/parser/assign.v
  vlib/v/pref/pref.v
  vlib/v/scanner/scanner.v
  vlib/v/tests/enum_default_value_in_struct_test.v
  vlib/v/tests/enum_test.v
  vlib/v/token/token.v
  vlib/x/json2/json2_test.v
  vlib/x/json2/scanner.v
Labels: hacktoberfest-accepted

#15952 checker, native: check arguments of native builtin functions
  vlib/v/checker/fn.v
  vlib/v/gen/native/tests/atexpr.vv
  vlib/v/gen/native/tests/atexpr.vv.out
Labels: Hacktoberfest

#15948 arrays, maps: Add indexed variant of collection function and minor cleanup
  vlib/arrays/arrays.v
  vlib/arrays/arrays_test.v
  vlib/maps/maps.v
  vlib/maps/maps_test.v
Labels: Hacktoberfest

#15958 native: support simple library calls
  vlib/v/gen/native/amd64.v
  vlib/v/gen/native/elf.v
  vlib/v/gen/native/gen.v
  vlib/v/gen/native/tests/libc.vv
  vlib/v/gen/native/tests/libc.vv.out
Labels: Hacktoberfest

#15961 net: add unsafe block to int -> enum cast
  vlib/net/net_windows.c.v
Labels: Hacktoberfest

#15960 arrays, maps: Refactor function signature and comment cleanup
  vlib/arrays/arrays.v
  vlib/arrays/arrays_test.v
  vlib/maps/maps.v
Labels: Hacktoberfest

#16001 builtin.array : Deprecate array.reduce
  vlib/builtin/array.v
  vlib/v/gen/native/amd64.v
Labels: Hacktoberfest

#16265 custom_error.v
  examples/custom_error.v
Labels: Unit: Examples, Hacktoberfest, hacktoberfest-accepted
