Repository vlang/v, pull requests merged in 2022-04, with the labels that each got.

#13824 checker: type inference over a generic type should compile
  vlib/rand/rand.v
  vlib/v/checker/check_types.v
  vlib/v/checker/checker.v
  vlib/v/checker/tests/generic_type_inference.out
  vlib/v/checker/tests/generic_type_inference.vv
Labels: Generics<T>

#13889 checker: fixes overloading operation when the type is optimized
  vlib/v/checker/fn.v
  vlib/v/parser/fn.v
  vlib/v/tests/operator_overloading_on_struct_with_too_many_fields_test.v
Labels: Unit: Type System

#13939 cgen: fix error for const using nested optionals (fix #13914)
  vlib/v/gen/c/cgen.v
  vlib/v/gen/c/fn.v
  vlib/v/tests/const_use_nested_optionals_test.v
Labels: Unit: Compiler

#13941 cgen: fix error for dereference mut interface in loop (fix #13913)
  vlib/v/gen/c/fn.v
  vlib/v/tests/dereference_mut_interface_in_loop_test.v
  vlib/v/tests/known_errors/testdata/README.md
Labels: Unit: Compiler

#13949 ci: introduce v benchmarks inside the ci workflow
  .github/workflows/ci_v_benchmark.yml
Labels: V Benchmarks

#14080 vlib: fixed bst child access if root is none
  vlib/datatypes/bstree.v
  vlib/datatypes/bstree_test.v
  vlib/v/checker/tests/check_err_msg_with_generics.out
Labels: datatype
