Repository vlang/v, pull requests merged in 2023-07, with the labels that each got.

#18851 cgen: fix return option call (fix #18848)
  vlib/v/gen/c/cgen.v
  vlib/v/tests/return_option_call_test.v
Labels: Unit: cgen, Option type

#18889 builtin: reduce the number of array allocations done for consts in all V programs
  vlib/math/bits/bits.v
  vlib/math/bits/bits_tables.v
  vlib/strconv/atofq.c.v
  vlib/strconv/f32_str.c.v
  vlib/strconv/f64_str.c.v
  vlib/strconv/f64_str.v
  vlib/strconv/format.v
  vlib/strconv/tables.v
  vlib/v/builder/interpreterbuilder/v_interpret_test.v
  vlib/v/eval/expr.v
  vlib/v/eval/object.v
  vlib/v/gen/c/cgen.v
Labels: Type: Optimization

#18914 math.big: improve is_power_of_2
  vlib/math/big/integer.v
Labels: Type: Optimization

#19015 gg: Android specific asset load in `create_image` function
  vlib/gg/image.c.v
Labels: OS: Android, Breaking Change
