Repository vlang/v, pull requests merged in 2023-04, with the labels that each got.

#17849 cgen: Fix result of typeof function returns result type
  vlib/v/gen/c/auto_str_methods.v
  vlib/v/tests/typeof_type_test.v
Labels: Unit: Compiler, Unit: cgen

#17853 cgen: Fix mutli return variable ignore in if guard
  vlib/v/gen/c/if.v
  vlib/v/gen/c/testdata/multi_return_ignored_if_guard.out
  vlib/v/gen/c/testdata/multi_return_ignored_if_guard.vv
Labels: Unit: Compiler, Unit: cgen

#17879 cgen: Fix wrong indent generation in anon fn decl
  vlib/v/gen/c/fn.v
Labels: Unit: cgen

#17375 flag: fix typo in vlib/flag uknown flag struct
  vlib/flag/flag.v
Labels: Meta: Good First Issue

#17997 add `-skip_line_length_check` flag and fixed `vmod` handling in '```vmod'
  cmd/tools/vcheck-md.v
Labels: check-md

#17058 json2: feat: encode from reference
  vlib/x/json2/encode_struct_test.v
  vlib/x/json2/encode_struct_todo_test.vv
  vlib/x/json2/encoder.v
  vlib/x/json2/json2.v
  vlib/x/json2/json_module_compatibility_test/json_test.v
  vlib/x/json2/json_module_compatibility_test/json_todo_test.vv
Labels: Need rebase
