Repository vlang/v, pull requests merged in 2023-02, with the labels that each got.

#17197 v: forbid local variable names, shadowing imported module names
  doc/docs.md
  vlib/builtin/string_test.v
  vlib/net/websocket/websocket_client.v
  vlib/v/checker/assign.v
  vlib/v/checker/tests/var_decl_import_sym_conflict.out
  vlib/v/checker/tests/var_decl_import_sym_conflict.vv
  vlib/v/pref/should_compile.v
Labels: Unit: Checker

#17208 docs: removed note about shadowng of import name due 0b7a1cd
  doc/docs.md
Labels: Unit: Documentation

#17224 cgen: fix assigning option of struct fntype field (fix #17223)
  vlib/v/gen/c/assign.v
  vlib/v/tests/assign_option_of_struct_fntype_field_test.v
Labels: Unit: cgen

#17210 v: forbid function parameter names, shadowing imported module names
  .github/workflows/v_apps_and_modules_compile_ci.yml
  cmd/tools/measure/parser_speed.v
  cmd/tools/measure/scanner_speed.v
  cmd/tools/vast/cjson.v
  cmd/tools/vast/vast.v
  cmd/tools/vfmt.v
  cmd/tools/vpm.v
  cmd/tools/vscan.v
  examples/database/orm.v
  vlib/compress/deflate/deflate.v
  vlib/compress/gzip/gzip.v
  vlib/compress/zlib/zlib.v
  vlib/rand/rand.v
  vlib/rand/sys/system_rng.c.v
  vlib/toml/parser/parser.v
  vlib/toml/toml.v
  vlib/v/README.md
  vlib/v/ast/type_size_test.v
  vlib/v/builder/builder.v
  vlib/v/builder/compile.v
  vlib/v/callgraph/callgraph.v
  vlib/v/checker/assign.v
  vlib/v/checker/checker.v
  vlib/v/checker/fn.v
  vlib/v/checker/tests/fn_param_import_sym_conflict.out
  vlib/v/checker/tests/fn_param_import_sym_conflict.vv
  vlib/v/doc/doc.v
  vlib/v/eval/eval.v
  vlib/v/fmt/fmt.v
  vlib/v/gen/c/cgen.v
  vlib/v/gen/c/cheaders.v
  vlib/v/gen/golang/golang.v
  vlib/v/gen/js/js.v
  vlib/v/gen/native/gen.v
  vlib/v/markused/markused.v
  vlib/v/parser/parser.v
  vlib/v/parser/v_parser_test.v
  vlib/v/scanner/scanner.v
  vlib/v/slow_tests/repl/runner/runner.v
  vlib/v/tests/cross_assign_test.v
  vlib/v/tests/fn_type_only_argument_test.v
  vlib/v/tests/modules/submodules/submodules_test.v
  vlib/v/tests/websocket_logger_interface_should_compile_test.v
  vlib/v/transformer/transformer.v
  vlib/v/util/module.v
Labels: Unit: Checker

#17188 v.reflection: add type symbol info metadata
  vlib/v/gen/c/cgen.v
  vlib/v/gen/c/fn.v
  vlib/v/gen/c/reflection.v
  vlib/v/reflection/reflection.v
  vlib/v/tests/reflection_sym_test.v
  vlib/v/tests/reflection_test.v
Labels: Unit: vlib

#17291 docs: format with IDEA formatter
  doc/docs.md
Labels: Unit: Documentation

#17294 docs: unify format of notes
  CONTRIBUTING.md
  README.md
  ROADMAP.md
  TESTS.md
  doc/docs.md
  doc/upcoming.md
  doc/vscode.md
  examples/regex/readme.md
  tutorials/building_a_simple_web_blog_with_vweb/README.md
  vlib/db/mysql/README.md
  vlib/db/pg/README.md
  vlib/dl/README.md
  vlib/encoding/binary/README.md
  vlib/eventbus/README.md
  vlib/gx/README.md
  vlib/js/README.md
  vlib/rand/README.md
  vlib/regex/README.md
  vlib/strconv/format.md
  vlib/v/TEMPLATES.md
  vlib/v/help/FORMATTING.md
  vlib/v/preludes/README.md
  vlib/v/tests/project_with_tests_for_main/README.md
  vlib/x/ttf/README.md
Labels: Unit: Documentation

#17293 docs: format with IDEA formatter other .md files
  CONTRIBUTING.md
Labels: Unit: Documentation

#17302 cgen, checker: fix comptimeselector resolution + if comptime branching improvement + comptimeselector cleanup
  vlib/v/ast/str.v
  vlib/v/checker/assign.v
  vlib/v/checker/check_types.v
  vlib/v/checker/checker.v
  vlib/v/checker/comptime.v
  vlib/v/checker/for.v
  vlib/v/checker/if.v
  vlib/v/checker/postfix.v
  vlib/v/checker/struct.v
  vlib/v/checker/tests/comptime_dump_fields_var_test.out
  vlib/v/gen/c/assign.v
  vlib/x/json2/encoder.v
Labels: Unit: Checker, Unit: cgen
